filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Evening Murpholinox, Welcome to Coot version 0.9")
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good evening Murpholinox. Welcome to Coot 0.9")
set_display_lists_for_maps (1)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/home/murphy/Repos/defensa/difference_map_nanao/2blx-coot-0.pdb", 1)
get_show_symmetry ()
get_show_unit_cell (0)
set_show_symmetry_master (1)
set_show_symmetry_master (1)
set_show_unit_cells_all (0)
set_symmetry_atom_labels_expanded (0)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
make_and_draw_map_with_reso_with_refmac_params ("/home/murphy/Repos/defensa/difference_map_nanao/2bly_phases.mtz", "FWT", "PHWT", "", 0, 0, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0,  0.00,  0.00)
make_and_draw_map_with_reso_with_refmac_params ("/home/murphy/Repos/defensa/difference_map_nanao/2bly_phases.mtz", "DELFWT", "PHDELWT", "", 0, 1, 0, "Fobs:None-specified", "SigF:None-specified", "RFree:None-specified", 0, 0, 0,  0.00,  0.00)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
;; # DIRECT SCHEME ((command-in-path-or-absolute? *probe-command*))
graphics_molecule_bond_type (0)
close_molecule (0)
filter_fileselection_filenames_state ()
filter_fileselection_filenames_state ()
handle_read_draw_molecule_with_recentre ("/home/murphy/Repos/defensa/difference_map_nanao/2blx.pdb", 1)
graphics_molecule_bond_type (4)
set_clipping_front (-0.40)
set_clipping_back (-0.80)
;; # DIRECT SCHEME ((graphics-general-key-press-hook 65))
accept_baton_position ()
set_add_alt_conf_split_type_number (1)
show_select_map_dialog ()
show_select_map_dialog ()
setup_torsion_general (1)
setup_torsion_general (0)
do_rot_trans_setup (1)
rot_trans_reset_previous ()
do_rot_trans_setup (1)
rot_trans_reset_previous ()
rot_trans_reset_previous ()
show_select_map_dialog ()
show_select_map_dialog ()
setup_rotamers (1)
setup_rotamers (0)
set_undo_molecule (4)
apply_undo ()
setup_edit_chi_angles (1)
setup_edit_chi_angles (0)
set_show_chi_angle_bond (0)
set_show_chi_angle_bond (0)
show_select_map_dialog ()
show_select_map_dialog ()
setup_edit_chi_angles (1)
setup_edit_chi_angles (0)
set_show_chi_angle_bond (0)
set_show_chi_angle_bond (0)
set_add_alt_conf_split_type_number (1)
set_add_alt_conf_split_type_number (0)
show_select_map_dialog ()
show_select_map_dialog ()
show_select_map_dialog ()
set_delete_residue_mode ()
delete_residue_with_full_spec (4, 1, "A", 80, "", "B")
clear_pending_delete_item ()
delete_residue_by_atom_index (4, 647, 1)
set_add_alt_conf_split_type_number (1)
first_coords_imol ()
first_unsaved_coords_imol ()
