(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Evening Murpholinox, Welcome to Coot version 0.9")
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good evening Murpholinox. Welcome to Coot 0.9")
(set-display-lists-for-maps 1)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/home/murphy/Repos/defensa/difference_map_nanao/2blx-coot-0.pdb" 1)
(get-show-symmetry)
(get-show-unit-cell 0)
(set-show-symmetry-master 1)
(set-show-symmetry-master 1)
(set-show-unit-cells-all 0)
(set-symmetry-atom-labels-expanded 0)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(make-and-draw-map-with-reso-with-refmac-params "/home/murphy/Repos/defensa/difference_map_nanao/2bly_phases.mtz" "FWT" "PHWT" "" 0 0 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(make-and-draw-map-with-reso-with-refmac-params "/home/murphy/Repos/defensa/difference_map_nanao/2bly_phases.mtz" "DELFWT" "PHDELWT" "" 0 1 0 "Fobs:None-specified" "SigF:None-specified" "RFree:None-specified" 0 0 0  0.00  0.00)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(command-in-path-or-absolute? *probe-command*)
(graphics-molecule-bond-type 0)
(close-molecule 0)
(filter-fileselection-filenames-state)
(filter-fileselection-filenames-state)
(handle-read-draw-molecule-with-recentre "/home/murphy/Repos/defensa/difference_map_nanao/2blx.pdb" 1)
(graphics-molecule-bond-type 4)
(set-clipping-front -0.40)
(set-clipping-back -0.80)
(graphics-general-key-press-hook 65)
(accept-baton-position)
(set-add-alt-conf-split-type-number 1)
(show-select-map-dialog)
(show-select-map-dialog)
(setup-torsion-general 1)
(setup-torsion-general 0)
(do-rot-trans-setup 1)
(rot-trans-reset-previous)
(do-rot-trans-setup 1)
(rot-trans-reset-previous)
(rot-trans-reset-previous)
(show-select-map-dialog)
(show-select-map-dialog)
(setup-rotamers 1)
(setup-rotamers 0)
(set-undo-molecule 4)
(apply-undo)
(setup-edit-chi-angles 1)
(setup-edit-chi-angles 0)
(set-show-chi-angle-bond 0)
(set-show-chi-angle-bond 0)
(show-select-map-dialog)
(show-select-map-dialog)
(setup-edit-chi-angles 1)
(setup-edit-chi-angles 0)
(set-show-chi-angle-bond 0)
(set-show-chi-angle-bond 0)
(set-add-alt-conf-split-type-number 1)
(set-add-alt-conf-split-type-number 0)
(show-select-map-dialog)
(show-select-map-dialog)
(show-select-map-dialog)
(set-delete-residue-mode)
(delete-residue-with-full_spec 4 1 "A" 80 "" "B")
(clear-pending-delete-item)
(delete-residue-by-atom-index 4 647 1)
(set-add-alt-conf-split-type-number 1)
(first-coords-imol)
(first-unsaved-coords-imol)
