/cmd.set('internal_gui',1,'',0)
_ viewport (\
_   860.000000000,  513.000000000 )
util.performance(0)
rebuild
cmd.disable('2bly_2fo-fc')
cmd.disable('2bly_fo-fc_pos')
cmd.disable('2bly_fo-fc_neg')
cmd.disable('2bly')
cmd.enable('2blx',1)
/cmd.set('opaque_background',1,'',0)
/cmd.set('bg_rgb',0,'',0)
cmd.show("mesh","c2-c1_neg")
cmd.show("mesh","c2-c1_pos")
load diff.map
cmd.disable('c2-c1_neg')
cmd.enable('c2-c1_neg',1)
cmd.color_deep("violet", 'c2-c1_neg', 0)
cmd.select('sele','none')
cmd.select('sele',"byresi((((sele) or byresi((2blx`1117))) and not ((byresi((2blx`1117))) and byresi(sele))))",enable=1)
cmd.center("(2blx`226)",state=1)
cmd.select('sele',"byresi((((sele) or byresi((2blx`895))) and not ((byresi((2blx`895))) and byresi(sele))))",enable=1)
cmd.center("(2blx`895)",state=1)
cmd.select('sele',"byresi((((sele) or byresi((2blx`93))) and not ((byresi((2blx`93))) and byresi(sele))))",enable=1)
cmd.center("(2blx`93)",state=1)
cmd.select('sele',"byresi((((sele) or byresi((2blx`987))) and not ((byresi((2blx`987))) and byresi(sele))))",enable=1)
cmd.center("(2blx`987)",state=1)
cmd.select('sele',"byresi((((sele) or byresi((2blx`329))) and not ((byresi((2blx`329))) and byresi(sele))))",enable=1)
cmd.center("(2blx`329)",state=1)
cmd.select('sele',"byresi((((sele) or byresi((2blx`730))) and not ((byresi((2blx`730))) and byresi(sele))))",enable=1)
cmd.center("(2blx`730)",state=1)
cmd.select('sele',"byresi((((sele) or byresi((2blx`636))) and not ((byresi((2blx`636))) and byresi(sele))))",enable=1)
cmd.center("(2blx`636)",state=1)
cmd.disable('sele')
cmd.select('sele','none')
cmd.select('sele',"byresi((((sele) or byresi((2blx`545))) and not ((byresi((2blx`545))) and byresi(sele))))",enable=1)
cmd.disable('sele')
cmd.mouse('select_forward')
cmd.mouse('select_forward')
cmd.mouse('select_forward')
cmd.mouse('select_forward')
cmd.mouse('select_forward')
